/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary": "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-gold": "var(--color-secondary-gold)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "surface": "var(--color-surface)",
        "on-surface": "var(--color-on-surface)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "surface-tint": "var(--color-surface-tint)",
        "outline": "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "error": "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        "background": "var(--color-background)",
        "on-background": "var(--color-on-background)",
        "buttercream": "var(--color-buttercream)",
        "buttercream-light": "var(--color-buttercream-light)",
        "accent-glow": "var(--color-accent-glow)",
        "dark-surface": "var(--color-surface)",
        "dark-surface-dim": "var(--color-surface-dim)",
        "dark-surface-container": "var(--color-surface-container)",
        "dark-surface-container-high": "var(--color-surface-container-high)",
        "dark-surface-container-highest": "var(--color-surface-container-highest)",
        "dark-surface-container-low": "var(--color-surface-container-low)",
        "dark-on-surface": "var(--color-on-surface)",
        "dark-on-surface-variant": "var(--color-on-surface-variant)",
        "dark-outline": "var(--color-outline)",
        "dark-outline-variant": "var(--color-outline-variant)",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-2xs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "space-2xl": "4rem",
        "space-3xl": "6rem",
        "space-4xl": "8rem",
        "gutter-desktop": "2rem",
        "gutter-tablet": "1.5rem",
        "gutter-mobile": "1rem",
        "container-max": "1440px",
      },
      fontFamily: {
        serif: ['"DM Serif Display"', 'Georgia', 'serif'],
        sans: ['"Inter"', 'system-ui', '-apple-system', 'sans-serif'],
        "display-hero": ['"DM Serif Display"', 'serif'],
        "headline-lg": ['"DM Serif Display"', 'serif'],
        "headline-md": ['"DM Serif Display"', 'serif'],
        "headline-sm": ['"DM Serif Display"', 'serif'],
        "body-lg": ['"Inter"', 'sans-serif'],
        "body-md": ['"Inter"', 'sans-serif'],
        "body-sm": ['"Inter"', 'sans-serif'],
        "label-caps": ['"Inter"', 'sans-serif'],
        "label-md": ['"Inter"', 'sans-serif'],
        "price-editorial": ['"DM Serif Display"', 'serif'],
      },
      fontSize: {
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["28px", { lineHeight: "36px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "price-editorial": ["22px", { lineHeight: "28px", fontWeight: "400" }],
      },
      boxShadow: {
        "gold-sm": "0 4px 20px -4px rgba(184, 142, 62, 0.08)",
        "gold-md": "0 8px 24px -4px rgba(197, 160, 89, 0.15)",
        "gold-lg": "0 24px 48px -12px rgba(24, 22, 21, 0.12), 0 8px 24px -4px rgba(197, 160, 89, 0.15)",
      },
      screens: {
        'xs': '475px',
      }
    },
  },
  plugins: [],
};
